export const modalBackground ="bg-gray-500 bg-transparent fixed inset-0 z-50 flex justify-center items-center"
export const modalContainer = "rounded-lg w-auto h-1/2 flex justify-between items-center bg-white shadow-lg flex flex-col p-6 ease-in-out duration-300"
export const closeBtn = "text-black ml-auto mt-auto mb-6"
export const modalTitle = " text-xl text-center text-black mb-24"
export const modalBody = "flex justify-center text-black items-center text-center text-base mb-36"
export const modalFooter = "flex justify-around items-center"
export const footerBtnConfirmar = "w-36 h-11 m-2.5 text-sm border-none bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 rounded-lg text-white"
export const footerBtnCancelar = "w-36 h-11 ml-6 border color-white text-base rounded-lg hover:bg-white-800 focus:ring-4 focus:outline-none focus:ring-blue-300"
